CREATE TABLE prototype_comment (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  public_id CHAR(26) NOT NULL UNIQUE,
  prototype_id BIGINT NOT NULL,
  version_id BIGINT NOT NULL,
  parent_id BIGINT NULL,
  content TEXT NOT NULL,
  status VARCHAR(16),
  author_type VARCHAR(16) NOT NULL,
  author_user_id BIGINT NULL,
  guest_name VARCHAR(100),
  share_link_id BIGINT NULL,
  resolved_by BIGINT NULL,
  resolved_at TIMESTAMP(6),
  resolve_note VARCHAR(500),
  row_version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP(6) NOT NULL,
  deleted_at TIMESTAMP(6),
  FOREIGN KEY (prototype_id) REFERENCES prototype(id),
  FOREIGN KEY (version_id) REFERENCES prototype_version(id),
  FOREIGN KEY (parent_id) REFERENCES prototype_comment(id),
  FOREIGN KEY (share_link_id) REFERENCES prototype_share_link(id),
  FOREIGN KEY (author_user_id) REFERENCES sys_user(id),
  FOREIGN KEY (resolved_by) REFERENCES sys_user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
